'use client';

import React from 'react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import {
  Sparkles,
  ArrowRight,
  BookOpen,
  DollarSign,
  MapPin,
  GraduationCap,
  Globe,
  FileText,
} from 'lucide-react';
import { cn } from '@/lib/utils';

export interface RelatedQuestion {
  id: string;
  question: string;
  icon?: React.ComponentType<{ className?: string }>;
  category?: string;
}

export interface RelatedQuestionsProps {
  questions: RelatedQuestion[];
  onQuestionClick: (question: string) => void;
  className?: string;
}

const defaultIcons = [BookOpen, DollarSign, MapPin, GraduationCap, Globe, FileText];

export const RelatedQuestions: React.FC<RelatedQuestionsProps> = ({
  questions,
  onQuestionClick,
  className,
}) => {
  if (!questions || questions.length === 0) {
    return null;
  }

  return (
    <div className={cn("space-y-3 animate-in fade-in slide-in-from-bottom-4 duration-150", className)}>
      {/* Header */}
      <div className="flex items-center gap-2 px-2">
        <Sparkles className="h-4 w-4 text-[#F5A576]" />
        <span className="text-sm font-medium text-foreground">
          Related Questions
        </span>
      </div>

      {/* Questions grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
        {questions.map((question, index) => {
          const Icon = question.icon || defaultIcons[index % defaultIcons.length];

          return (
            <Card
              key={question.id}
              className={cn(
                "group relative overflow-hidden border-none bg-card shadow-sm hover:shadow-md",
                "transition-all duration-150 hover:scale-[1.01]",
                "cursor-pointer"
              )}
              onClick={() => onQuestionClick(question.question)}
            >
              <Button
                variant="ghost"
                className="w-full h-auto p-4 justify-start items-start text-left hover:bg-transparent"
              >
                <div className="flex items-start gap-3 w-full">
                  {/* Icon */}
                  <div className="flex-shrink-0 w-8 h-8 rounded-lg bg-gradient-to-br from-[#F5A576]/10 to-[#F08F5E]/10 flex items-center justify-center group-hover:from-[#F5A576]/20 group-hover:to-[#F08F5E]/20 transition-all duration-150 shadow-sm">
                    <Icon className="h-4 w-4 text-[#F5A576]" />
                  </div>

                  {/* Question text */}
                  <div className="flex-1 min-w-0">
                    <p className="text-sm text-foreground group-hover:text-[#F5A576] transition-colors duration-150 leading-relaxed">
                      {question.question}
                    </p>
                    {question.category && (
                      <span className="text-xs text-muted-foreground mt-1 inline-block">
                        {question.category}
                      </span>
                    )}
                  </div>

                  {/* Arrow icon */}
                  <ArrowRight className="flex-shrink-0 h-4 w-4 text-muted-foreground group-hover:text-[#F5A576] group-hover:translate-x-1 transition-all duration-150 opacity-0 group-hover:opacity-100" />
                </div>
              </Button>

              {/* Gradient overlay */}
              <div className="absolute inset-0 bg-gradient-to-br from-[#F5A576]/0 to-[#F5A576]/0 group-hover:from-[#F5A576]/5 group-hover:to-[#F08F5E]/5 transition-all duration-150 pointer-events-none" />
            </Card>
          );
        })}
      </div>
    </div>
  );
};

// Helper function to generate contextual related questions
export const generateRelatedQuestions = (
  context: string,
  previousQuestions: string[] = []
): RelatedQuestion[] => {
  // This is a simple example - in production, this would be generated by AI
  const questionBank: Record<string, RelatedQuestion[]> = {
    universities: [
      {
        id: '1',
        question: 'What are the admission requirements?',
        icon: FileText,
        category: 'Admissions',
      },
      {
        id: '2',
        question: 'How much does it cost to study there?',
        icon: DollarSign,
        category: 'Finance',
      },
      {
        id: '3',
        question: 'What scholarships are available?',
        icon: GraduationCap,
        category: 'Funding',
      },
      {
        id: '4',
        question: 'What is the application deadline?',
        icon: BookOpen,
        category: 'Timeline',
      },
    ],
    scholarships: [
      {
        id: '1',
        question: 'What are the eligibility criteria?',
        icon: FileText,
        category: 'Requirements',
      },
      {
        id: '2',
        question: 'How do I apply for this scholarship?',
        icon: BookOpen,
        category: 'Application',
      },
      {
        id: '3',
        question: 'When is the application deadline?',
        icon: Globe,
        category: 'Timeline',
      },
      {
        id: '4',
        question: 'Can I apply to multiple scholarships?',
        icon: GraduationCap,
        category: 'Strategy',
      },
    ],
    costs: [
      {
        id: '1',
        question: 'What is the cost of living in this city?',
        icon: MapPin,
        category: 'Location',
      },
      {
        id: '2',
        question: 'Are there any financial aid options?',
        icon: DollarSign,
        category: 'Aid',
      },
      {
        id: '3',
        question: 'Can I work part-time while studying?',
        icon: GraduationCap,
        category: 'Work',
      },
      {
        id: '4',
        question: 'What are the tuition payment options?',
        icon: FileText,
        category: 'Payment',
      },
    ],
    default: [
      {
        id: '1',
        question: 'Tell me more about study abroad options',
        icon: Globe,
        category: 'General',
      },
      {
        id: '2',
        question: 'What are the best universities for my field?',
        icon: GraduationCap,
        category: 'Research',
      },
      {
        id: '3',
        question: 'How do I prepare my application?',
        icon: FileText,
        category: 'Application',
      },
      {
        id: '4',
        question: 'What is the typical timeline for applications?',
        icon: BookOpen,
        category: 'Timeline',
      },
    ],
  };

  // Determine context type
  let questionSet = questionBank.default;
  const lowerContext = context.toLowerCase();

  if (lowerContext.includes('university') || lowerContext.includes('college')) {
    questionSet = questionBank.universities;
  } else if (lowerContext.includes('scholarship') || lowerContext.includes('funding')) {
    questionSet = questionBank.scholarships;
  } else if (lowerContext.includes('cost') || lowerContext.includes('fee') || lowerContext.includes('tuition')) {
    questionSet = questionBank.costs;
  }

  // Filter out questions that have already been asked
  return questionSet.filter(
    (q) => !previousQuestions.some((prev) => prev.toLowerCase().includes(q.question.toLowerCase()))
  );
};
